### ISSUE TITLE
Why threads instead of glue?

### ISSUE THREAD

**Issue by Arkonos** [rsayko/SpoolWinder#3]
I wonder why you chose to use threads, which are rather time consuming to print, instead of either gluing the sides together.
Is repairability plausible in the first place?

Перекладено за допомогою ChatGPT 3.5:
Цікаво, чому ви вирішили використовувати різьблення, яке досить часовитратне для друку, замість того, щоб просто склеїти боковини. Чи можлива ремонтопридатність взагалі?

**Comment by rsayko** [comment]
Hello, thank you for your suggestions. We use threads because the item must occupy as little space as possible for shipping, and it needs to be assembled without requiring any additional components.
