### ISSUE TITLE
Getting rid of the tool

### ISSUE THREAD

**Issue by Arkonos** [rsayko/SpoolWinder#4]
While trying to make my own version using Inventor, I thought about two ways to make the tool for turning obsolete.

1. Change the base of one of the cylinders to a square, as seen in this image.

![image](https://github.com/rsayko/SpoolWinder/assets/3932266/90a6603d-a02b-4240-8d54-43df6431ccd3)

This would make one of the two sides self locking.

2. Instead of a big hexagonal hole, a simple slit dimensioned for a coin, knife, etc would suffice to be able to twist the parts together.
A slit with Length: 27, Width: 2.5, Depth: 27mm would accommodate 1 hryvnia, 1 dollar and 2 euro coins.

Перекладено за допомогою ChatGPT 3.5:
Прагнучи створити власну версію за допомогою Inventor, я подумав про два способи виготовлення інструмента для обертання застарілим.

1. Змініть основу одного з циліндрів на квадрат, як показано на цьому зображенні.

![image](https://github.com/rsayko/SpoolWinder/assets/3932266/90a6603d-a02b-4240-8d54-43df6431ccd3)

Це зробить одну з двох сторін самозахоплюючою.

2. Замість великої шестигранної отвору вистачить простої щілини з розмірами для монети, ножа і т.д., щоб можна було скрутити деталі разом. Щілина з довжиною: 27, шириною: 2,5, глибиною: 27 мм буде відповідати монетам у 1 гривню, 1 долар та 2 євро.

**Comment by rsayko** [comment]
While a self-locking mechanism is a good idea, it is not as forgiving as threading (I mean, if you insert slightly incorrect values in OpenScad). Other than that, it will not be easy to implement such a mechanism in OpenScad that can be adapted to any size of the spool.

**Comment by Arkonos** [comment]
I have no experience with OpenScad, so I'll trust your opinion.
The way I scale it in inventor is to set the inner width of the square to the diametre of the inner hole of the spool and the outer to a non-scaling 5 mm.

But before I continue to develop my own design a couple of questions:
- Is a competing design desired at all? I have access to Inventor and would be willing to supply derivative stls for various spool sizes. 
- If a spool breaks during usage, is it brought back for repair or just thrown away?
- Do you have a minimum and maximum spool size in mind? I have 1-5 kg at home that I could test.
- Should the spools be able to spin?

I've created a new room should you want to discuss this more privately: t.me/+p6SzrXDfK6cyYzE8

**Comment by rsayko** [comment]
> Is a competing design desired at all? I have access to Inventor and would be willing to supply derivative stls for various spool sizes. 

We have made most popular sizes with Fusion360, this version is for exceptional cases

> If a spool breaks during usage, is it brought back for repair or just thrown away? 

Depends, replace part or new one can be sent

> Should the spools be able to spin? 

No

**Comment by Arkonos** [comment]
Thank you

Since repairability is a goal, I'll refrain from doing my own version and try to print yours again.
